fragment PostParts on Post {
  __typename
  title
  abstract
  banner
  banner_placeholder
  date
  body
}

fragment FeaturedParts on Featured {
  __typename
  post {
    ... on Post {
      __typename
      title
      abstract
      banner
      banner_placeholder
      date
      body
    }
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
}
